apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "pod-cleanup.fullname" . }}
  labels:
  {{- include "pod-cleanup.labels" . | nindent 4 }}
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - command:
            - sh
            - -c
            - kubectl delete pods --field-selector status.phase==Failed --all-namespaces
            image: {{ .Values.podCleanup.cleanupContainer.image.repository }}:{{
              .Values.podCleanup.cleanupContainer.image.tag | default .Chart.AppVersion
              }}
            name: cleanup-container
            resources: {}
          restartPolicy: OnFailure
          serviceAccountName: {{ include "pod-cleanup.fullname" . }}
  schedule: {{ .Values.podCleanup.schedule | quote }}