apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "pod-cleanup.fullname" . }}-pod-cleanup
  labels:
  {{- include "pod-cleanup.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.podCleanup.serviceAccount.annotations | nindent 4 }}